# Render Deployment Configuration
services:
  - type: web
    name: energy-predictor-ai
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python deploy_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000